player.onChat("buildtunnel", function () {
        // 通道參數a
            let tunnelLength = 20; // L 格，通道長度
                let tunnelHalfWidth = 6; // 半寬：6格
                    let tunnelHalfHeight = 6; // 半高：6格

                        // 獲取玩家當前位置
                            let playerPos = player.position();
                                let playerX = playerPos.x;
                                    let playerY = playerPos.y;
                                        let playerZ = playerPos.z;

                                            // 獲取玩家水平朝向 (Yaw)，範圍通常是 -180 到 180
                                                // 0度: 南 (+Z)
                                                    // 90度: 東 (-X)
                                                        // 180度/-180度: 北 (-Z)
                                                            // -90度: 西 (+X)
                                                                let playerYaw = player.rotation(); // 獲取玩家水平旋轉角度

                                                                    // 根據玩家朝向判斷建造方向
                                                                        let startX, startY, startZ; // 通道外框的起始點
                                                                            let endX, endY, endZ;     // 通道外框的結束點
                                                                                let innerStartX, innerStartY, innerStartZ; // 通道內部的起始點
                                                                                    let innerEndX, innerEndY, innerEndZ;     // 通道內部的結束點

                                                                                        // 方塊類型：透明玻璃 (Block.Glass)
                                                                                            let glassBlock = Block.Glass;
                                                                                                let airBlock = Block.Air;

                                                                                                    // 判斷玩家最接近哪個主軸方向
                                                                                                        // 為了簡化邏輯，我們將角度轉換為 0-360 範圍，並調整為標準羅盤方向
                                                                                                            // 0度為北，90度為東，180度為南，270度為西
                                                                                                                let normalizedYaw = (playerYaw + 360) % 360; // 轉換到 0-360 範圍
                                                                                                                    
                                                                                                                        // 根據角度判斷方向
                                                                                                                            // 北 (-Z): 315 度到 45 度 (或 -45 到 45)
                                                                                                                                // 東 (-X): 45 度到 135 度
                                                                                                                                    // 南 (+Z): 135 度到 225 度
                                                                                                                                        // 西 (+X): 225 度到 315 度

                                                                                                                                            if (normalizedYaw >= 315 || normalizedYaw < 45) { // 朝向 北 (-Z)
                                                                                                                                                    game.say("建造通道：朝向北方 (-Z)");
                                                                                                                                                            startX = playerX - tunnelHalfWidth;
                                                                                                                                                                    endX = playerX + tunnelHalfWidth;
                                                                                                                                                                            startY = playerY - tunnelHalfHeight;
                                                                                                                                                                                    endY = playerY + tunnelHalfHeight;
                                                                                                                                                                                            startZ = playerZ - 1; // 從玩家後方一格開始建造，避免玩家被困住
                                                                                                                                                                                                    endZ = playerZ - tunnelLength;

                                                                                                                                                                                                            innerStartX = startX + 1;
                                                                                                                                                                                                                    innerEndX = endX - 1;
                                                                                                                                                                                                                            innerStartY = startY + 1;
                                                                                                                                                                                                                                    innerEndY = endY - 1;
                                                                                                                                                                                                                                            innerStartZ = startZ - 1;
                                                                                                                                                                                                                                                    innerEndZ = endZ + 1;

                                                                                                                                                                                                                                                        } else if (normalizedYaw >= 45 && normalizedYaw < 135) { // 朝向 東 (-X)
                                                                                                                                                                                                                                                                game.say("建造通道：朝向東方 (-X)");
                                                                                                                                                                                                                                                                        startX = playerX - 1; // 從玩家後方一格開始建造
                                                                                                                                                                                                                                                                                endX = playerX - tunnelLength;
                                                                                                                                                                                                                                                                                        startY = playerY - tunnelHalfHeight;
                                                                                                                                                                                                                                                                                                endY = playerY + tunnelHalfHeight;
                                                                                                                                                                                                                                                                                                        startZ = playerZ - tunnelHalfWidth;
                                                                                                                                                                                                                                                                                                                endZ = playerZ + tunnelHalfWidth;

                                                                                                                                                                                                                                                                                                                        innerStartX = startX - 1;
                                                                                                                                                                                                                                                                                                                                innerEndX = endX + 1;
                                                                                                                                                                                                                                                                                                                                        innerStartY = startY + 1;
                                                                                                                                                                                                                                                                                                                                                innerEndY = endY - 1;
                                                                                                                                                                                                                                                                                                                                                        innerStartZ = startZ + 1;
                                                                                                                                                                                                                                                                                                                                                                innerEndZ = endZ - 1;

                                                                                                                                                                                                                                                                                                                                                                    } else if (normalizedYaw >= 135 && normalizedYaw < 225) { // 朝向 南 (+Z)
                                                                                                                                                                                                                                                                                                                                                                            game.say("建造通道：朝向南方 (+Z)");
                                                                                                                                                                                                                                                                                                                                                                                    startX = playerX - tunnelHalfWidth;
                                                                                                                                                                                                                                                                                                                                                                                            endX = playerX + tunnelHalfWidth;
                                                                                                                                                                                                                                                                                                                                                                                                    startY = playerY - tunnelHalfHeight;
                                                                                                                                                                                                                                                                                                                                                                                                            endY = playerY + tunnelHalfHeight;
                                                                                                                                                                                                                                                                                                                                                                                                                    startZ = playerZ + 1; // 從玩家前方一格開始建造
                                                                                                                                                                                                                                                                                                                                                                                                                            endZ = playerZ + tunnelLength;

                                                                                                                                                                                                                                                                                                                                                                                                                                    innerStartX = startX + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                            innerEndX = endX - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    innerStartY = startY + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            innerEndY = endY - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    innerStartZ = startZ + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            innerEndZ = endZ - 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else { // 朝向 西 (+X) (normalizedYaw >= 225 && normalizedYaw < 315)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        game.say("建造通道：朝向西方 (+X)");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                startX = playerX + 1; // 從玩家前方一格開始建造
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endX = playerX + tunnelLength;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                startY = playerY - tunnelHalfHeight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endY = playerY + tunnelHalfHeight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                startZ = playerZ - tunnelHalfWidth;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endZ = playerZ + tunnelHalfWidth;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                innerStartX = startX + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        innerEndX = endX - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                innerStartY = startY + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        innerEndY = endY - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                innerStartZ = startZ + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        innerEndZ = endZ - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 建造外部玻璃框架 (實心玻璃長方體)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 注意：setBlocks 函數的參數順序是 (x1, y1, z1, x2, y2, z2, blockType)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 並且它會自動處理 x1 > x2 的情況，所以可以直接使用計算出的起始和結束點
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            blocks.fill(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    glassBlock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            world(startX, startY, startZ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    world(endX, endY, endZ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FillOperation.Replace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 在內部填充空氣，形成中空通道
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 確保內部空間至少為 1x1x1，否則無法挖空
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (Math.abs(innerEndX - innerStartX) >= 0 && Math.abs(innerEndY - innerStartY) >= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    blocks.fill(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                airBlock,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            world(innerStartX, innerStartY, innerStartZ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        world(innerEndX, innerEndY, innerEndZ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FillOperation.Replace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        game.say("通道內部空間不足，無法挖空。請檢查半寬/半高設定。");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                game.say("透明玻璃通道建造完成！");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
})